---
title: "RWorksheet_Soteo#4b"
output: pdf_document
date: "2023-11-22"
---

```{r num 1}
#1.
vectorA <- c(1,2,3,4,5)
matrixA <- matrix(0, nrow = 5, ncol = 5)
print(matrixA)

for (i in 1:5) {
  for (j in 1:5) {
    matrixA[i,j] <- abs(vectorA[i] - vectorA[j])
  }
}

print(matrixA)
```

```{r num 2}
#2. 
num_lines <- 5

for (i in 1:num_lines) {
  for (j in 1:i) {
    cat("*")
  }
  cat("\n")
}

```

```{r num 3}
#3.
start_num <- as.integer(readline(prompt = "Enter the starting number: "))

if (start_num < 0) {
  print("Invalid input. Please enter a positive integer.")
  quit()
}

num1 <- start_num
num2 <- start_num + 1

repeat {
  print(num1)
  
  next_num <- num1 + num2
  num2 <- num1
  num1 <- next_num
  
  if (next_num > 500){
    break
  }
}
```

```{r num 4}
#4.A
shoeSize_tab <- read.csv("Shoe_sizes.csv")
shoeSize_tab

head(shoeSize_tab)
```

```{r num 5}
#B
male_subset <- subset(shoeSize_tab, Gender == "M")
male_subset
female_subset <- subset(shoeSize_tab, Gender == "F")
female_subset

#There are 5 observations in male subset, and 9 observations in female subset.
```

```{r}
GraphMF<- table(shoeSize_tab$Gender)
barplot(GraphMF,
        main = "Number of Males and Females",
        xlab = "Gender",
        ylab = "Count",
        col = c("dodgerblue4", "hotpink4"),
        legend.text = c("Male", "Female"),
        beside = TRUE
)
```


```{r num5}
Expenses <- c(Food = 60, Electricity = 10, Savings = 5, Miscellaneous = 25)

pie(Expenses,
    labels = paste(names(Expenses), "\n", sprintf("%.1f%%", prop.table(Expenses) * 100)),
    col = c("blue", "yellow", "red", "green"),  
    main = "Monthly Expenses of the Dela Cruz Family"
)
```

```{r num6a}

data("iris")
str(iris)

#The iris dataset has 150 observations and 5 variables.
#These variables are the Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, and Species.
```
``` {r num6b}
MeanIris<- colMeans(iris[, c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width")])
print(MeanIris)
```


```{r num6c}
Spec <- table(iris$Species)

clors <- c("midnightblue", "mediumvioletred", "mediumblue")

pie(Spec,
    labels = paste(names(Spec), "\n", sprintf("%.1f%%", prop.table(Spec) * 100)),
    col = clors,
    main = "Species Distribution",
    cex.main = 1.5,
    cex = 0.8      
)
```

``` {r num6d}
SetosaSub <- subset(iris, Species == "setosa")
VersiSub <- subset(iris, Species == "versicolor")
VirgiSub <- subset(iris, Species == "virginica")

# Display the last six rows of each species
cat("Last six rows of Setosa:")
print(tail(SetosaSub))

cat("Last six rows of Versicolor:")
print(tail(VersiSub))

cat("Last six rows of Virginica:")
print(tail(VirgiSub))
```

``` {r num6e}

data(iris)

iris$Species <- as.factor(iris$Species)

plot(iris$Sepal.Length, iris$Sepal.Width,
     pch = as.integer(iris$Species),
     col = iris$Species,
     main = "Iris Dataset",
     sub = "Sepal width and length",
     xlab = "Sepal Length",
     ylab = "Sepal Width"
)
```

``` {r num6f}
#The scatterplot shows similarities between the sepal width and length ranging from 5.5 to 7.0
```

```{r num7a}
library(readxl)
alexa_file <- read_excel("alexa_file.xlsx")
alexa_file
```